CREATE DATABASE TestDB
GO

USE TestDb 

CREATE TABLE Customers
(
Id INT PRIMARY KEY IDENTITY,
Age INT DEFAULT 18, 
FirstName NVARCHAR(20) NOT NULL,
LastName NVARCHAR(20) NOT NULL,
Email VARCHAR(30) UNIQUE,
Phone VARCHAR(20) UNIQUE
);

CREATE TABLE Orders 
(
Id INT IDENTITY,
CustomerId INT, 
CreateAt Date
);

GO
ALTER TABLE Customers 
ADD Address NVARCHAR(50) NULL ;

GO
ALTER TABLE Customers
ADD Sex VARCHAR(1) NOT NULL;

GO
ALTER TABLE Customers 
ADD Sex VARCHAR(1) NOT NULL DEFAULT 'M';

GO
ALTER TABLE Customers
DROP COLUMN Address

GO
ALTER TABLE Customers
ALTER COLUMN FirstName NVARCHAR(200)

GO
ALTER TABLE Customers 
ADD CHECK (Age > 21);

GO
ALTER TABLE Customers WITH NOCHECK
ADD CHECK (Age > 21);

GO
ALTER TABLE Orders
ADD FOREIGN KEY (CustomerId) REFERENCES Customers(Id);

GO
ALTER TABLE Orders
ADD PRIMARY KEY (Id);

GO
ALTER TABLE Orders
ADD CONSTRAINT PK_Orders_Id PRIMARY KEY (Id),
	CONSTRAINT FK_Orders_To_Customers FOREIGN KEY(CustomerId) REFERENCES Customers(Id);

GO
ALTER TABLE Customers
ADD CONSTRAINT CK_Age_Greater_Than_100 CHECK (Age <= 100); 

GO
ALTER TABLE Customers
DROP CK_Age_Greater_Than_100;

GO
CREATE TABLE Adress
(
Id INT PRIMARY KEY IDENTITY,
City NVARCHAR(20) DEFAULT 'Майкоп',
Street NVARCHAR(20),
HouseNumber INT CHECK(HouseNumber > 0)
);

GO
ALTER TABLE Adress 
ADD PRIMARY KEY(ID)

GO
ALTER TABLE Customers
ADD AddressId INT;

GO
ALTER TABLE Customers
ADD CONSTRAINT FK_Orders_To_Customers FOREIGN KEY(CustomerId) REFERENCES Customers(Id);

GO
ALTER TABLE Customers
ADD CONSTRAINT FK_TO_Customers FOREIGN KEY (AddressId) REFERENCES Adress(ID)
